### ISSUE TITLE
Clone failed on windows cause file system doesnt support character '<' and '>' on windows.

### ISSUE THREAD

**Issue by PommesPeter** [visualDust/ml.akasaki.space#10]
如题

**Comment by visualDust** [comment]
shit

**Comment by visualDust** [comment]
we arch users haven't ever never notice that.

**Comment by visualDust** [comment]
problem fixed. you can continue your work now.

**Comment by PommesPeter** [comment]
Clone failed again because the image path has not fixed.

**Comment by visualDust** [comment]
that's odd.....

**Comment by PommesPeter** [comment]
> have you tried to delete the whole project folder and clone it again?

I have tried this way. But I can't delete it directly, because when I push the del button, nothing working. I think I should run my arch to delete it.

**Comment by visualDust** [comment]
握草，好家伙，个个下班跟投胎似的

**Comment by PommesPeter** [comment]
> okay, maybe you should delete the project folder on your Linux since the operation on windows may have some strange problem on files with characters '<' and '>' in their name.

yep

**Comment by visualDust** [comment]
I think the problem was solved right?
I'm going to close this issue.
