### ISSUE TITLE
something was wrong!about it! in the 魔法部日志's readme

### ISSUE THREAD

**Issue by zeroRains** [visualDust/ml.akasaki.space#105]
请具体描述是什么导致你在[本仓库的网页版](https://ml.akasaki.space/)阅读体验下降
或描述哪里出现了格式或引用错误的问题
![image](https://user-images.githubusercontent.com/57100978/121683620-3845ea80-caf0-11eb-97e1-ba5143391388.png)

**Comment by visualDust** [comment]
pu

**Comment by visualDust** [comment]
I'll fix it soon

**Comment by visualDust** [comment]
#110  fixed
