### ISSUE TITLE
这里可以改成图像增强，图像增广不是太贴切

### ISSUE THREAD

**Issue by coronaPolvo** [visualDust/ml.akasaki.space#120]
请具体描述是什么导致你在[本仓库的网页版](https://ml.akasaki.space/)阅读体验下降
或描述哪里出现了格式或引用错误的问题
![image](https://user-images.githubusercontent.com/55493212/125912402-505708cc-cc1c-4d5a-9e1e-af9e8071da26.png)

**Comment by coronaPolvo** [comment]
@visualDust

**Comment by visualDust** [comment]
这里是想写关于 image augmentation 技术的简单例子。但是由于种种原因还没有开始，所以这篇文章暂时没有完成。

**Comment by visualDust** [comment]
图像增强是指：
> 增强图像中的有用信息，它可以是一个失真的过程，其目的是要改善图像的视觉效果，针对给定图像的应用场合。 有目的地强调图像的整体或局部特性，将原来不清晰的图像变得清晰或强调某些感兴趣的特征，扩大图像中不同物体特征之间的差别，抑制不感兴趣的特征，使之改善图像质量、丰富信息量，加强图像判读和识别效果，满足某些特殊分析的需要。

以上内容来自百度百科。
