### ISSUE TITLE
寻找一个像样的模板存放魔法部日志

### ISSUE THREAD

**Issue by visualDust** [visualDust/ml.akasaki.space#43]
如题，不管是hexo还是vuepress啥的，好看实用就行
（目前的目标是hexo-butterfly

**Comment by lideming** [comment]
🐟画一个就有了

**Comment by coronaPolvo** [comment]
butterfly 不香吗？

**Comment by BreezeShane** [comment]
建议用fluid，样例可以看我的博客breezeshane.github.io

**Comment by coronaPolvo** [comment]
> 建议用fluid，样例可以看我的博客breezeshane.github.io
> 省心省事，美观实用，内嵌LaTeX渲染和mermaid渲染

blog.keter.top
这个好看

**Comment by visualDust** [comment]
唔，过两天忙完学校的工程认证翻翻上述主题。这两天暂时没空了...

**Comment by zeroRains** [comment]
> 唔，过两天忙完学校的工程认证翻翻上述主题。这两天暂时没空了...

hexo相对路径好像不太友好

**Comment by visualDust** [comment]
对，感觉不是很友好（
之前还想直接用hexo+butterfly来着...

**Comment by BreezeShane** [comment]
相对路径不太友好？我还真没这感觉，这个是咋回事？

**Comment by visualDust** [comment]
> 相对路径不太友好？我还真没这感觉，这个是咋回事？

大概就是相对路径生成html的时候带不上的样子（
