### ISSUE TITLE
Unable to run "git add ." cause filename too long

### ISSUE THREAD

**Issue by PommesPeter** [visualDust/ml.akasaki.space#45]
Another error that occurs on windows is when I running "git add ." command, it failed. Error message is
`error: open("docs/unlimited-paper-works/src/Threat-of-Adversarial-Attacks-on-Deep-Learning-in-Computer-Vision-A-Survey/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L3B5dGhvbl9MQ19ub2h0eXA=,size_16,color_FFFFFF,t_70-20210501181805986.png"): Filename too long`

@visualDust

**Comment by lideming** [comment]
https://stackoverflow.com/a/22575737

Try `git config --system core.longpaths true`

**Comment by PommesPeter** [comment]
> https://stackoverflow.com/a/22575737
> 
> Try `git config --system core.longpaths true`

okay

**Comment by visualDust** [comment]
stmd，我直接没看见
