### ISSUE TITLE
增加对注意力的介绍

### ISSUE THREAD

**Issue by X1J1AN** [visualDust/ml.akasaki.space#56]
如题

**Comment by visualDust** [comment]
on schedule. Your request will be finished in one week.

**Comment by BreezeShane** [comment]
Waiting for it ! I think it worthy~😃😃😃

**Comment by visualDust** [comment]
@Asthestarsfalll solved this. #71

**Comment by visualDust** [comment]
#

**Comment by visualDust** [comment]
currently adding attention part into ch3p2 at #85 , not finished yet.

**Comment by visualDust** [comment]
waiting for #84 fix first

**Comment by visualDust** [comment]
#84 fixed by #87

**Comment by visualDust** [comment]
#93 almost finished

**Comment by visualDust** [comment]
@X1J1AN now you can read this at [this page](https://ml.akasaki.space/ch3p2/%5B4%5Dattention.html#%E9%94%AE%E5%80%BC%E5%AF%B9%E5%AE%9E%E7%8E%B0%E6%B3%A8%E6%84%8F%E5%8A%9B)

**Comment by visualDust** [comment]
#95 almost finished.
