### ISSUE TITLE
增加对清华提出的EA和EAMLP的介绍

### ISSUE THREAD

**Issue by coronaPolvo** [visualDust/ml.akasaki.space#89]
增加对清华提出的EA和EAMLP的介绍， @Asthestarsfalll

**Comment by visualDust** [comment]
We found this paper as [Beyond Self-attention: External Attention using Two Linear Layers for Visual Tasks](https://arxiv.org/abs/2105.02358)

**Comment by visualDust** [comment]
This won't take too long. Maybe next week you'll see our note.

**Comment by coronaPolvo** [comment]
> This won't take too long. Maybe next week you'll see our note.

I can't find czh

**Comment by visualDust** [comment]
Then do it manully.
@Asthestarsfalll

**Comment by Asthestarsfalll** [comment]
I find this issue just now, I‘ll do if time premits
